CREATE TABLE account (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INT NOT NULL,
    firstName VARCHAR(31) NOT NULL,
    lastName VARCHAR(31) NOT NULL,
    username VARCHAR(20) NOT NULL,
    pass_hash VARCHAR(256) NOT NULL
);

