DROP TABLE IF EXISTS account;
CREATE TABLE account (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(31) NOT NULL,
    last_name VARCHAR(31) NOT NULL,
    username VARCHAR(20) NOT NULL,
    pass_hash VARCHAR(256) NOT NULL
);
GRANT ALL ON account TO bv_user;
