DROP TABLE IF EXISTS department;
CREATE TABLE department (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    zipcode NUMERIC(5) NOT NULL,
    overall_rating DECIMAL(3,2) NOT NULL CHECK (overall_rating >= 1 AND overall_rating <= 5)
   
);
GRANT ALL ON department TO bv_user;
