CREATE TABLE post_reply (
    reply_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    parent_post_id INT NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    user_id INT NOT NULL,
    text VARCHAR(1023) NOT NULL
);

