CREATE TABLE post (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    date_of_incident DATE NOT NULL,
    title VARCHAR(63) NOT NULL, 
    body VARCHAR(1023) NOT NULL, 
    user_id INT NOT NULL,
    department_id INT NOT NULL
);

