CREATE TABLE post (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    department_id INT NOT NULL,
    date_of_incident DATE NOT NULL,
    title VARCHAR(63) NOT NULL, 
    body VARCHAR(1023) NOT NULL, 
    FOREIGN KEY (id) REFERENCES post_reply (id)
);

